### PR TITLE
Add Julia submodule

### PR DESCRIPTION
**Pull request by cbrnr**
This adds a Julia submodule. Fixes https://github.com/xdf-modules/pyxdf/issues/72.

### CODE REVIEW

**Comment by cbrnr** [comment]
@cboulay feel free to merge.

**Comment by chkothe** [comment]
This submodule doesn't correctly mount for me when I clone the repo and/or pull the latest -- could it be that `git submodule add` wasn't used to add it?

**Comment by cboulay** [comment]
In addition to adding the .gitmodules change to the commit, @cbrnr forgot to add the `Julia` placeholder folder. I missed it when I merged. Sorry about that.

Now fixed.

**Comment by cbrnr** [comment]
Thanks @cboulay!

**Pull request merged**
