### PR TITLE
Added C++ libxdf

### PR DESCRIPTION
**Pull request by Yida-Lin**
Hi guys!

Sorry for the delay, here is the C++ XDF loader, that Clemens @cbrnr and I have been working on in the past year. It was specifically tailored for SigViewer so it may not align exactly as the MATLAB and Python loader, but overall it serves the purpose of loading and resampling XDF files well. Any advice on improvements would be appreciated.

Best,
Yida

### CODE REVIEW

**Comment by cboulay** [comment]
Hi @Yida-Lin ,

Discussion about libxdf has popped up again because we're worried about diverging matlab/python/labrecorder features. If we do end up making a libxdf then it would be nice if your library served as the starting point.

I've invited you at the xdf-modules organization. Would you be willing to make libxdf a separate repository and transferring it to that organization? You will still have full control over that repository.

I'm going to close this PR because it doesn't fit in this top-level repository, but it would be a very welcome addition to the xdf-modules organization.

**Comment by Yida-Lin** [comment]
Hi @cboulay ,

Thanks for following up on this issue; I am more than happy to let the current libxdf serve as a starting point for the potential module.

The only problem I see is that, SigViewer (@cbrnr ) depends on the current version of libxdf, and if libxdf is modified, it may become incompatible with SigViewer. Or did I misunderstand that, you meant duplicating the libxdf repo first, then transferring it into the xdf repo?

Thanks

**Comment by cboulay** [comment]
It's better to not have duplicated code.

If you don't already have a libxdf repo, then I propose you create one in the xdf-modules group. From there we'll create a tag for its current state. SigViewer can link against this commit/tag.

Then we (you, me, @tstenner, anyone else interested) will modify the library so that it is useful in LabRecorder, the Python importer, and the Matlab importer. Hopefully it won't be too much work to also update SigViewer to be able to use this new version of the library, but SigViewer can continue to use the old version until that happens.

How does that sound?

**Comment by cboulay** [comment]
https://github.com/organizations/xdf-modules/repositories/new

**Comment by Yida-Lin** [comment]
@cboulay Sounds great, I have just finished transferring.

**Comment by cboulay** [comment]
By the way, along similar lines, if you want then we can also put SigVisualizer in the github.com/labstreaminglayer organization. Again, you'll have full control over it. I recommend it to people all of the time so it would be good if it were more visible, and maybe others will collaborate on it to help iron out the bugs when there are multiple streams.
Let me know!

**Comment by Yida-Lin** [comment]
@cboulay I agree, I never had enough time resource to finish SigVisualizer so it would be great if there are more hands to work on it. Sounds good to me.

**Comment by cboulay** [comment]
For the smoothest transition with SigVisualizer, I think first you need to add me as an admin to the repo so I can transfer its ownership to labstreaminglayer group, then I will add you back as an admin to the SigVisualizer repo.

I'm on my way out the door right now so I won't be able to do this for about 4 or 5 hours.

**Comment by Yida-Lin** [comment]
I didn't see a way to add admin in Settings.

Alternatively, you could add me to the labstreaminglayer group, and I will transfer it just like libxdf.

**Comment by cboulay** [comment]
Sorry I meant add as a collaborator. https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository
Once added you can change my permissions between Read, Write, and Admin. That last one should give me power to transfer the repo.

Unlike the xdf org, for the labstreaminglayer org we are trying to keep the organization-level members down to the same core group. Individual repos within the organization can be admin'd by outsiders.

If I can't transfer the repo then I'll add you temporarily, probably tomorrow.

**Comment by Yida-Lin** [comment]
@cboulay I see, great. I thought you are already a collaborator at https://github.com/Yida-Lin/SigVisualizer
so hopefully it already works.

**Comment by cboulay** [comment]
Ah, I see that collaborators can't transfer user repositories, only the owner can. OK, then can you transfer the repository to me first, then I will transfer it to labstreaminglayer?

**Comment by Yida-Lin** [comment]
You may need to delete your forked repo before I can transfer

**Comment by Yida-Lin** [comment]
image

**Comment by cboulay** [comment]
Sorry! Done.

**Comment by Yida-Lin** [comment]
@cboulay Cool, done here as well.

**Comment by cboulay** [comment]
https://github.com/labstreaminglayer/App-SigVisualizer
Now we need someone to go through the sccn/labstreaminglayer Wiki and create alternate Python-only tutorials to supplement the Matlab tutorials, but that's for another day.

**Comment by Yida-Lin** [comment]
@cboulay Sounds great! Could you please share a link to the Matlab tutorials?

**Comment by cboulay** [comment]
They're just in the Wiki. See the menubar on the right here: https://github.com/sccn/labstreaminglayer/wiki

**Pull request closed without merging**
